name: Push to nuget feed on release

on:
  release:
    types: [published]
    
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Setup Nuget
      uses: nuget/setup-nuget@v1
      
    - name: Nuget pack
      run: |
        nuget restore
        nuget pack ConfigurationManager\ConfigurationManager.cs